runtime:
  cache_dir: ./.cache/antora
site:
  title: Community Collaboration Guide
  url: https://redhat-documentation.github.io
  start_page: community::introduction
content:
  sources:
  - url: .
    branches: HEAD
asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    linkattrs: ''
ui:
  bundle:
    url: https://github.com/finp/antora-ui/raw/master/build/ui-bundle.zip
    snapshot: true

