// tag::split-creating_reference_modules.adoc[]
[id="creating-reference-modules"]
= Creating Reference Modules

This section explains what a reference module is and provides recommended practices for writing reference modules.

:leveloffset: +1

[id="reference-module-definition"]
= Reference Module Definition

Reference modules provide data that users might want to look up, but do not need to remember.

.Common documentation examples of reference modules
====
* A list of commands that users can use with an application
* A table of configuration files with definitions and usage examples
* A list of default settings for a product
====

.Reference modules explained using a real-life example
====
For documentation on how to cross the road, you could create these modules:

* Concept modules:
** What are roads
** What are crossings

* Procedure modules:
** How to put one foot in front of another
** How to use pedestrian traffic lights
** How to see if the road is clear for crossing

* Reference modules:
** Crossing signals
** Common crosswalk pavement markings
** Crossing laws by country
====

:leveloffset: 1

:leveloffset: +1

[id="reference-module-guidelines"]
= Reference Module Guidelines

The required part of a reference module is the reference data.
A reference module requires a short introduction.

[discrete]
== Reference Introduction

The introduction to a reference module is a single, concise paragraph that provides a short overview of the module. A short description makes the module more usable because users can quickly determine whether the reference is useful without having to read the entire module.

[discrete]
== Reference Body

A reference module has a very strict structure, often in the form of a list or a table. A well-organized reference module enables users to scan it quickly to find the details they want.

To make the reference data easier to scan, organize it in a logical order (such as alphabetically) or as a table. AsciiDoc markup to consider for reference data:

* link:http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#lists[Lists] (unordered, labeled)
* link:http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#tables[Tables]

If you have a large volume of the same type of information to document, use a structure into which the information details can fit, and then document each logical unit of information as one reference module. For example, think of man pages, which document very different information details, but which still use consistent titles and formats to present those details in a uniform information structure.

:leveloffset: 1

== Additional Resources

* Download the link:https://raw.githubusercontent.com/redhat-documentation/modular-docs/master/modular-docs-manual/files/TEMPLATE_REFERENCE_reference-material.adoc[reference module template (adoc file)] for new projects.
* For real-world examples of reference modules, see <<modular-docs-reference-examples>>.
* For advice on when to use lists and when to use tables, see link:https://medium.com/@heyoka/lets-bring-table-to-the-table-again-f1ae751159d5[Let’s bring <table> to the table, again.]
// end::split-creating_reference_modules.adoc[]
